### ISSUE TITLE
login failing

### ISSUE THREAD

**Issue by isisis** [zendframework/modules.zendframework.com#370] opened 2015-02-06 21:58 UTC
When I try to login with my Github account here ...

http://modules.zendframework.com/user/loing

I'm getting redirected to this url ...

http://modules.zendframework.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

Seems like there's a problem with the github login. Just wanted to add my first module to the list.

**Comment by ins0** [comment] 2015-02-06 22:05
duplicate #300 #296

**Comment by isisis** [comment] 2015-02-06 22:11
Sorry, didn't see the duplicate ...
But I'd suggest to leave this one opened on the first page. Is Ocramius already aware of it?
Someone working on a solution?

**Comment by ins0** [comment] 2015-02-06 22:13
thanks for your report.
yes @GeeH is working on this as this fix needs server access

**Comment by IgorDePaula** [comment] 2015-02-08 01:14
I can't login too.

**Comment by IgorDePaula** [comment] 2015-02-08 01:15
And I put module in site already.

**Comment by ins0** [comment] 2015-02-08 01:35
please spam https://twitter.com/GeeH as he is currently working to fix this :trollface:

**Comment by isisis** [comment] 2015-02-08 04:05
Seems like there's no bug in the application, but in the Github api. Why not use normal - on site - authentication? I can't see any advantages on using Github authentication.
Instead one could make the application user associatable to Github user. This way users would still be able to login, even if the Github api will strike again.

**Comment by IgorDePaula** [comment] 2015-02-08 13:27
Where I see normal authtentication?

2015-02-08 2:05 GMT-02:00 Ibrahim Süzük <notifications@github.com>:

**Comment by ins0** [comment] 2015-02-08 13:28
as i said this needs more access to the application that only @GeeH can provide. i don't see any advantages to use a normal login as the only use-case to register a module is to add a module from github - so please be more specific what advantage u see when using a normal login. maybe in the future when more user features are available this comes in handy, no?

**Comment by gianarb** [comment] 2015-02-08 13:35
@IgorDePaula the normale authentication is from Github.. In this moment this site support only github site and move it from another adapter isn't a priority.
I don't believe that the problem is in Github Api :+1: In this moment @GeeH is engaged SunShinePHP!! :) 
I hope that it could work about it as soon as possible but change all auth method for me is not necessary

**Comment by isisis** [comment] 2015-02-08 13:57
@ins0 Yes, the use-case is only adding github repositories, but with an on-site authentication one could also add new repos, even if the github authentication doesn't work currently, or not?
To my mind it's better to stay independent from a second application (github), as long as it's possible, but it's only my humble opinion.

**Comment by GeeH** [comment] 2015-02-08 13:58
I’ll need some help here. We should schedule a hangout to nail this down where I can screenshare.


On 8 February 2015 at 08:57:11, Ibrahim Süzük (notifications@github.com) wrote:

@ins0 Yes, the use-case is only adding github repositories, but with an on-site authentication one could also add new repos, even if the github authentication doesn't work currently, or not?
To my mind it's better to stay independent from a second application (github), as long as it's possible, but it's only my humble opinion.

**Comment by ins0** [comment] 2015-02-08 14:25
@isisis i agree it is just that the current process adding modules requires a linked github account - we are currently fixing many stuff that has accumulated over the time this repo was not really maintained - refactoring all classes and adding abstraction layers where switching to a normal signup don't require to recode all processes. so as @gianarb says this is currently not necessary - but yeah in the future we should replace the "only github login".

@GeeH 
ping me tomorrow in irc :+1:

**Comment by basz** [comment] 2015-02-12 22:31
@GeeH help offered, how can I help you to fix this issue?

**Comment by isisis** [comment] 2015-02-16 01:10
I don't understand why commits are being send to the repository, but no one fixes the authentication.
Did no one succeed fixing it or is the hosted project not being maintained anymore?
@basz offered help and I would help too, if I knew what's the current situation.

**Comment by Ocramius** [comment] 2015-02-16 01:11
I'll poke @GeeH tomorrow, and eventually ask for SSH data if he can't check it. Right now we're pretty much drowning in work :-\

**Comment by GeeH** [comment] 2015-02-16 09:01
The reason is because it takes time. Time I don’t have at the moment. I’m working two jobs and this week I’m spending some time with my family that is long overdue.

I hope this is OK with you.


On 16 February 2015 at 01:10:33, Ibrahim Süzük (notifications@github.com) wrote:

I don't understand why commits are being send to the repository, but no one fixes the authentication.
Did no one succeed fixing it or is the hosted project not being maintained anymore?
@basz offered help and I would help too, if I knew what's the current situation.

**Comment by ins0** [comment] 2015-02-16 09:12
@GeeH sure it is! Thanks for letting us notice. As @Ocramius said it would be nice if we can share the ssh login with marco as well so if one is busy we still can deploy on the production server. :smiley:

**Comment by GeeH** [comment] 2015-02-16 09:13
@Ocramius knows how to get access if he can run with it then great. Otherwise I will look this evening.


On 16 February 2015 at 09:12:19, Marco Rieger (notifications@github.com) wrote:

@GeeH sure it is! Thanks for letting us notice. As @Ocramius said it would be nice if we can share the ssh login with marco as well so if one is busy we still can deploy on the production server.

**Comment by ins0** [comment] 2015-02-16 09:14
@GeeH :+1:

**Comment by gianarb** [comment] 2015-02-16 09:15
The time is a shared problem but maybe we are here to help you to manage this project in the best way :+1:

**Comment by GeeH** [comment] 2015-02-16 11:24
As a point of note, the site is hosted on Roave server, and only Roave employees (or trusted third parties) can have access. If you wish to get access to the server with SSH please email “team@roave.com” making your case. Alternatively we can host somewhere else if anyone is willing to pay and Zend are happy with the arrangement.

G


On 16 February 2015 at 09:14:13, Marco Rieger (notifications@github.com) wrote:

@GeeH

**Comment by gianarb** [comment] 2015-02-16 11:31
@GeeH can you share with me google analytics data of the site?
gianarb92[at]gmail[dot]com

Thanks

**Comment by GeeH** [comment] 2015-02-16 11:32
I don’t have access to that sadly, chase up @Hounddog.


On 16 February 2015 at 11:31:48, Gianluca Arbezzano (notifications@github.com) wrote:

@GeeH can you share with me google analytics data of the site?
gianarb92[at]gmail[dot]com

Thanks

**Comment by gianarb** [comment] 2015-02-16 11:35
Thanks! :)

**Comment by localheinz** [comment] 2015-02-19 12:34
Well, this bug really is an annoyance!

**Comment by localheinz** [comment] 2015-02-19 12:46
As far as I can tell, this only needs a small change in the administrative panel of GitHub, see this screenshot from my application:

![screen shot 2015-02-19 at 13 42 08](https://cloud.githubusercontent.com/assets/605483/6266699/26319c76-b83d-11e4-8f97-5de3c5e1bca1.png)

I was able to reproduce the error by providing an **Authorization Callback URL** pointing to a different location. I assume it should be http://modules.zendframework.com. Maybe it's not? 

Someone with admin privileges, e.g., an owner, should be able to fix this, I believe.

/cc @ezimuel @weierophinney.

**Comment by localheinz** [comment] 2015-02-19 12:47
Unsure if this is related, but when you navigate to https://modules.zendframework.com, you'll see this:

![screen shot 2015-02-19 at 13 41 21](https://cloud.githubusercontent.com/assets/605483/6266757/d3294582-b83d-11e4-9bf1-a6a135541c75.png)

**Comment by IgorDePaula** [comment] 2015-02-19 12:53
@andreas, I don't understand you, please can you explain again?

2015-02-19 10:47 GMT-02:00 Andreas Möller <notifications@github.com>:

**Comment by localheinz** [comment] 2015-02-19 12:55
@IgorDePaula 

The point I'm making is that it might not even be necessary to SSH into the server to fix this issue, but instead might only need a glance / small change rather into the  [GitHub Application Settings](https://github.com/settings/applications) for this application! :wink:

**Comment by basz** [comment] 2015-02-19 12:57
@localheinz bet that's the solution to the login problem! ping @GeeH 

The https:// going to zend paackages issue is an apache/nigx configuration problem

**Comment by IgorDePaula** [comment] 2015-02-19 12:57
Ah, ok, I understand you now, thank you

2015-02-19 10:55 GMT-02:00 Andreas Möller <notifications@github.com>:

**Comment by localheinz** [comment] 2015-02-19 12:59
Closing this in favour of #296, as it's a duplicate - if you don't mind!

**Closed by localheinz** 2015-02-19 12:59 UTC
Labels: Bug, high priority
