### ISSUE TITLE
No sufficient permissions exception while trying to remove module from Registered Modules

### ISSUE THREAD

**Issue by emcode** [zendframework/modules.zendframework.com#155] opened 2013-10-29 18:02 UTC
Hello, I've tried to remove module which I created few months ago and published on modules.zendframework.com. I wanted to do this just to experiment and check how it will influence my "My Modules" tab (right now I have another module which does not show up there - but its another issue which is probably resolved already by [this pull request](https://github.com/zendframework/modules.zendframework.com/pull/154))

It seems that I have no permissions to remove module which I created - [AssetAliases](http://modules.zendframework.com/emcode/AssetAliases). Look at the screen which contains exception and one notice on top of the page: 

![selection_001](https://f.cloud.github.com/assets/1683194/1430312/9675f636-40bf-11e3-9620-8e4eb4dfd608.png)

Maybe you will have some ideas what might be wrong. As I mentioned before I also experienced [problems with module detection](https://github.com/zendframework/modules.zendframework.com/issues/140#issuecomment-25028300). 

Maybe those issues are somehow correlated ?

**Comment by gianarb** [comment] 2015-02-24 08:35
ping @emcode  :)

**Comment by localheinz** [comment] 2015-02-24 09:43
@emcode 

I just tried to reproduce the problem by submitting a module and then attempting to remove it, but was unable to reproduce the problem, that is, I succeeded removing the module.

Closing for now, feel free to re-open if you encounter the problem again.

**Closed by localheinz** 2015-02-24 09:43 UTC
